language: java
jdk: oraclejdk8
branches:
  only: master
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: w6fKVLGdOAfX3abLoPan718J9lYUDdpKkbfLKt/bcu/+OULjIxME2pYYCQEt2nS5p7DjEl+3XW2HP+YQbeV2kq3l8/D0M/bWhPKLlGC8usIVXQgimy0DlEl6wDhOhnH7eyFLs2+P4Pg7F2Xk/htlLlGFpcMCAsr/4kr3JM/aux5KlY6cvhefG8vfa2dPcaurvh06RuQqxyaPfN1D/2p/DV5ylU58+bwpyvkmbE/Tj9p3RR6xP70o1QekomcyGRumNaWSbKeYWwNl8TkIov6OMTnoRfbq1KJbJF+iaIxieod0jBTb1njE6XOVwXZjnI5KWlkYFMhPpkmB6DqlqTM94/oTFAmbeeSu+RhwiGdq3wUVdQ1EqaN5KgjrMoUzNwwpCGapqi68mjl8QTpIU9SoNbaEg4RcZNCQr7EFyY9j677nFEnzpSuLXCQpE4EVHGcpLqaBzjCbkpbLgaMZTLHpKmAVkn2gLP5W+sCefEDijE0gSCUVlNUzbmL9dVj0bQj4Uga8c0P4DWSWZW53DsyHjnsM620ot3a4bY3H9wsP9G2hhu4Ygxjo/Xry3VUoVoPht+gOkwzaRK8k3NpBL1XNwKiCxwXnbYtABv59a0a/hfd0NU8O4UQB6OC7m/tnfejnrI3CHxM8iYVxwHir07GiZUdHgXcEpBgMI+KLA4iMz7Y=
  - secure: hQkeTXDOOrCq2RkrJW6puwgsWS7LJ5sUq7qTHVfnibumnkqG53jHNlE3huWzXk+lLFPvIi7STieKW1StIeAF7UCklyGzE3USlP95aIA93ZlipLnnEt0pJHlgQ69C76O5VFLDkrDcP5CcRpJUq9iZJDtRMM+kylRlZwPWRIg7PtZ/ZeAEDBJyxSLPyM7WGwHNubc5frgH1jrAh/xYucMajhGcY3/jd9nrOIkOfQo065cS7J/2Mes5rv0HSMgtmkQ94WLIFzkHdybAA7usI9sSfwtMh1Rmz14DfPXj+ObA1EeO4keXov4R9z8te9/RmoS8YjRpD3jwLQAfeeZf79y34/hElBGbSn/4aFq6nKIEQKhLS/DCiaJ67KfP9AHkUixLDsC0Mzw5qMqIfVGjRj8t5jSMIIPUlSWGYfwaizA16YUo3CsvFthEvJLg1sMTLGllZgte14Otr3rOgGPhlMWgqt/wCdMvEThnKzrNNNlE1qVT4YUi5aJZ+jAILkSI9We9MpgjCXoDDuVRJFcNS8MbKVTzWS+Y2Go6EiCN2sbLL1tquLUBKjG6iqJwUQ9E8b7n3vyGaXQyg39CM8fRfTHhWBYcQ7+quv3lZmNDJ/POav2avws8HXaNe4W4s49vPT39OMzpLCsufFqZe6P/FY1dNq+NoBZ3sYx4+jMGuz7KO+Y=
